coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/mock/**"
  - "cmd/**"
  - "scripts/**"
  - "docs/**"
  - "assets/**"
  - "migrations/**"
  - "**/*.sql"
  - "internal/storage/s3.go" # S3 storage is production only code. instead, we test mock storage.
  - "internal/stack/client.go" # Container Provisioner HTTP client is production only code. instead, we test mock client.
  - "internal/stack/grpc_client.go" # Container Provisioner gRPC client is production only code. instead, we test mock client.
  - "internal/http/handlers/types.go" # only type definitions and constructors.
